import type { Metadata } from "next";
import "./globals.css";
import { ThemeProvider } from "./components/themeProvider";
import ReactLenis from "lenis/react";
import { ClerkProvider } from "@clerk/nextjs";

export const metadata: Metadata = {
  title: "Zortime",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <ClerkProvider>
        <html lang="en" suppressHydrationWarning>
          <head />
          <ReactLenis root>
            <body>
              <ThemeProvider
                attribute="class"
                defaultTheme="dark"
                enableSystem
                disableTransitionOnChange
              >
                {children}
              </ThemeProvider>
            </body>
          </ReactLenis>
        </html>
      </ClerkProvider>
    </>
  );
}
